export const LanguagesList = [
  {
    Image:
      "https://xtratheme.com/elementor/business-2/wp-content/uploads/sites/18/2018/01/logo1_fff-1.png",
  },
  {
    Image:
      "https://xtratheme.com/elementor/business-2/wp-content/uploads/sites/18/2018/01/logo3_fff-1.png",
  },
  {
    Image:
      "https://xtratheme.com/elementor/business-2/wp-content/uploads/sites/18/2018/01/logof_fff-1.png",
  },
  {
    Image:
      "https://xtratheme.com/elementor/business-2/wp-content/uploads/sites/18/2018/01/logo5_ffff-1.png",
  },
  {
    Image:
      "https://xtratheme.com/elementor/business-2/wp-content/uploads/sites/18/2018/01/logo2_fff-1.png",
  },
  {
    Image:
      "https://xtratheme.com/elementor/business-2/wp-content/uploads/sites/18/2018/01/logo8_fff-1.png",
  },
  {
    Image:
      "https://xtratheme.com/elementor/business-2/wp-content/uploads/sites/18/2018/01/logo5_ffff-1.png",
  },
  {
    Image:
      "https://xtratheme.com/elementor/business-2/wp-content/uploads/sites/18/2018/01/logo2_fff-1.png",
  },
];
